# Swagger specification for the Open edX API
# Note: not all API endpoints need to be listed here, just those that
#  are part of your Open edX installation's "public API".

---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Open edX"
host: "your-open-edx-site.org"
basePath: "/"
schemes:
- "https"

# Complete set of whitelisted routes.
# Upstream API owners: provide an fixed URI ref for each route.
paths:

  # Index
  "/":
    $ref: "./index.yaml#/endpoints/index"

  # Heartbeat
  "/heartbeat":
    $ref: "./heartbeat.yaml#/endpoints/heartbeat"

  # OAuth2
  "/oauth2/v1/access_token":
    $ref: "./oauth.yaml#/endpoints/request_access_token"

  # Catalog IDA
  "/catalog/v1/catalogs":
    $ref: "https://raw.githubusercontent.com/edx/course-discovery/649a4cb/api.yaml#/endpoints/v1/catalogs"
  "/catalog/v1/catalogs/{id}":
    $ref: "https://raw.githubusercontent.com/edx/course-discovery/649a4cb/api.yaml#/endpoints/v1/catalogById"
  "/catalog/v1/catalogs/{id}/courses":
      $ref: "https://raw.githubusercontent.com/edx/course-discovery/649a4cb/api.yaml#/endpoints/v1/catalogCourses"

  # Enterprise IDA
  "/enterprise/v1/catalogs":
    $ref: "https://raw.githubusercontent.com/edx/edx-enterprise/260055b/api.yaml#/endpoints/v1/enterpriseCatalogs"
  "/enterprise/v1/catalogs/{id}":
    $ref: "https://raw.githubusercontent.com/edx/edx-enterprise/260055b/api.yaml#/endpoints/v1/enterpriseCatalogById"
  "/enterprise/v1/catalogs/{id}/courses":
    $ref: "https://raw.githubusercontent.com/edx/edx-enterprise/260055b/api.yaml#/endpoints/v1/enterpriseCatalogCourses"
  "/enterprise/v1/enterprise-catalogs":
    $ref: "https://raw.githubusercontent.com/edx/edx-enterprise/260055b/api.yaml#/endpoints/v1/enterpriseCustomerCatalogs"
  "/enterprise/v1/enterprise-catalogs/{uuid}":
    $ref: "https://raw.githubusercontent.com/edx/edx-enterprise/260055b/api.yaml#/endpoints/v1/enterpriseCustomerCatalogByUuid"
  "/enterprise/v1/enterprise-catalogs/{uuid}/course-runs/{course_run_id}":
    $ref: "https://raw.githubusercontent.com/edx/edx-enterprise/260055b/api.yaml#/endpoints/v1/enterpriseCustomerCatalogCourseRunByUuid"
  "/enterprise/v1/enterprise-catalogs/{uuid}/courses/{course_key}":
    $ref: "https://raw.githubusercontent.com/edx/edx-enterprise/260055b/api.yaml#/endpoints/v1/enterpriseCustomerCatalogCourseByKey"
  "/enterprise/v1/enterprise-catalogs/{uuid}/programs/{program_uuid}":
    $ref: "https://raw.githubusercontent.com/edx/edx-enterprise/260055b/api.yaml#/endpoints/v1/enterpriseCustomerCatalogProgramByUuid"
  "/enterprise/v1/enterprise-customer/{uuid}/course-enrollments":
    $ref: "https://raw.githubusercontent.com/edx/edx-enterprise/260055b/api.yaml#/endpoints/v1/enterpriseCustomerCourseEnrollments"
  "/enterprise/v1/enterprise-customer/{uuid}/learner-summary":
    $ref: "https://raw.githubusercontent.com/edx/edx-enterprise-data/8fc95e4/api.yaml#/endpoints/v1/enterpriseCustomerLearnerSummary"

  # Registrar IDA
  "/registrar/api-docs":
    $ref: "https://raw.githubusercontent.com/edx/registrar/004ddd06fe24d7bff6f1fe55a254df9c3ae701b5/.api-generated.yaml#/endpoints/swagger"
  "/registrar/login":
    $ref: "https://raw.githubusercontent.com/edx/registrar/004ddd06fe24d7bff6f1fe55a254df9c3ae701b5/.api-generated.yaml#/endpoints/login"
  "/registrar/logout":
    $ref: "https://raw.githubusercontent.com/edx/registrar/004ddd06fe24d7bff6f1fe55a254df9c3ae701b5/.api-generated.yaml#/endpoints/logout"
  "/registrar/static/{proxy+}":
    $ref: "https://raw.githubusercontent.com/edx/registrar/004ddd06fe24d7bff6f1fe55a254df9c3ae701b5/.api-generated.yaml#/endpoints/static"
  "/registrar/v1-mock/jobs/{job_id}":
    $ref: "https://raw.githubusercontent.com/edx/registrar/004ddd06fe24d7bff6f1fe55a254df9c3ae701b5/.api-generated.yaml#/paths/~1v1-mock~1jobs~1{job_id}~1"
  "/registrar/v1-mock/programs":
    $ref: "https://raw.githubusercontent.com/edx/registrar/004ddd06fe24d7bff6f1fe55a254df9c3ae701b5/.api-generated.yaml#/paths/~1v1-mock~1programs~1"
  "/registrar/v1-mock/programs/{program_key}":
    $ref: "https://raw.githubusercontent.com/edx/registrar/004ddd06fe24d7bff6f1fe55a254df9c3ae701b5/.api-generated.yaml#/paths/~1v1-mock~1programs~1{program_key}~1"
  "/registrar/v1-mock/programs/{program_key}/enrollments":
    $ref: "https://raw.githubusercontent.com/edx/registrar/004ddd06fe24d7bff6f1fe55a254df9c3ae701b5/.api-generated.yaml#/paths/~1v1-mock~1programs~1{program_key}~1enrollments~1"
  "/registrar/v1-mock/programs/{program_key}/courses":
    $ref: "https://raw.githubusercontent.com/edx/registrar/004ddd06fe24d7bff6f1fe55a254df9c3ae701b5/.api-generated.yaml#/paths/~1v1-mock~1programs~1{program_key}~1courses~1"
  "/registrar/v1-mock/programs/{program_key}/courses/{course_id}/enrollments":
    $ref: "https://raw.githubusercontent.com/edx/registrar/004ddd06fe24d7bff6f1fe55a254df9c3ae701b5/.api-generated.yaml#/paths/~1v1-mock~1programs~1{program_key}~1courses~1{course_id}~1enrollments~1"

# edX extension point. Lists the vendors in use and their specific
#  parameters that are expected by upstream refs.
# Upstream API owners: document your dependencies in this index file to
#  avoid conflicts with other upstreams.
x-edx-api-vendors:
  aws_apigateway:
    stage_variables:
    - "id"
    - "landing_page"
    - "edxapp_host"
    - "discovery_host"
    - "enterprise_host"
    - "gateway_host"
    - "analytics_api_host"
    - "registrar_host"
