# Swagger specification for the Open edX API
# Note: not all API endpoints need to be listed here, just those that
#  are part of your Open edX installation's "public API".

---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Open edX"
host: "your-open-edx-site.org"
basePath: "/"
schemes:
- "https"

# Complete set of whitelisted routes.
# Upstream API owners: provide an fixed URI ref for each route.
paths:

  # Index
  "/":
    $ref: "./index.yaml#/endpoints/index"

  # Heartbeat
  "/heartbeat":
    $ref: "./heartbeat.yaml#/endpoints/heartbeat"

  # OAuth2
  "/oauth2/v1/access_token":
    $ref: "./oauth.yaml#/endpoints/request_access_token"

  # Catalog IDA
  "/catalog/v1/catalogs":
    $ref: "https://raw.githubusercontent.com/edx/course-discovery/cc0f678/api.yaml#/endpoints/v1/catalogs"
  "/catalog/v1/catalogs/{id}":
    $ref: "https://raw.githubusercontent.com/edx/course-discovery/cc0f678/api.yaml#/endpoints/v1/catalogById"
  "/catalog/v1/catalogs/{id}/courses":
      $ref: "https://raw.githubusercontent.com/edx/course-discovery/cc0f678/api.yaml#/endpoints/v1/catalogCourses"
  "/catalog/v1/search/all":
      $ref: "https://raw.githubusercontent.com/edx/course-discovery/cc0f678/api.yaml#/endpoints/v1/searchAll"
  "/catalog/v1/search/all/facets":
        $ref: "https://raw.githubusercontent.com/edx/course-discovery/cc0f678/api.yaml#/endpoints/v1/searchAllFacets"

  # Enterprise IDA
  "/enterprise/v1/catalogs":
    $ref: "https://raw.githubusercontent.com/edx/edx-enterprise/43ea09b/api.yaml#/endpoints/v1/enterpriseCatalogs"
  "/enterprise/v1/catalogs/{id}":
    $ref: "https://raw.githubusercontent.com/edx/edx-enterprise/43ea09b/api.yaml#/endpoints/v1/enterpriseCatalogById"
  "/enterprise/v1/catalogs/{id}/courses":
    $ref: "https://raw.githubusercontent.com/edx/edx-enterprise/43ea09b/api.yaml#/endpoints/v1/enterpriseCatalogCourses"

# edX extension point. Lists the vendors in use and their specific
#  parameters that are expected by upstream refs. 
# Upstream API owners: document your dependencies in this index file to
#  avoid conflicts with other upstreams.
x-edx-api-vendors:
  aws_apigateway:
    stage_variables:
    - "id"
    - "landing_page"
    - "edxapp_host"
    - "discovery_host"
    - "enterprise_host"
