# Swagger specification for the Open edX API
# Note: not all API endpoints need to be listed here, just those that
#  are part of your Open edX installation's "public API".

---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Open edX"
host: "your-open-edx-site.org"
basePath: "/"
schemes:
- "https"

# Complete set of whitelisted routes.
# Upstream API owners: provide an fixed URI ref for each route.
paths:

  # Index
  "/":
    $ref: "./index.yaml#/endpoints/index"

  # Heartbeat
  "/heartbeat":
    $ref: "./heartbeat.yaml#/endpoints/heartbeat"

  # OAuth2
  "/oauth2/v1/access_token":
    $ref: "./oauth.yaml#/endpoints/request_access_token"

  # Discovery IDA
  # Discovery and Catalog are both actually served from the course-discovery IDA
  # but we separate them here to distinguish between the different use cases
  "/discovery/v1/courses":
    $ref: "https://raw.githubusercontent.com/edx/course-discovery/96ea3a9/api.yaml#/endpoints/v1/courses"
  "/discovery/v1/courses/{uuid}":
    $ref: "https://raw.githubusercontent.com/edx/course-discovery/96ea3a9/api.yaml#/endpoints/v1/coursesByUuid"
  "/discovery/v1/programs":
    $ref: "https://raw.githubusercontent.com/edx/course-discovery/96ea3a9/api.yaml#/endpoints/v1/programs"
  "/discovery/v1/programs/{uuid}":
    $ref: "https://raw.githubusercontent.com/edx/course-discovery/96ea3a9/api.yaml#/endpoints/v1/programsByUuid"

  # Catalog IDA
  "/catalog/v1/catalogs":
    $ref: "https://raw.githubusercontent.com/edx/course-discovery/96ea3a9/api.yaml#/endpoints/v1/catalogs"
  "/catalog/v1/catalogs/{id}":
    $ref: "https://raw.githubusercontent.com/edx/course-discovery/96ea3a9/api.yaml#/endpoints/v1/catalogById"
  "/catalog/v1/catalogs/{id}/courses":
    $ref: "https://raw.githubusercontent.com/edx/course-discovery/96ea3a9/api.yaml#/endpoints/v1/catalogCourses"

  # Enterprise IDA
  "/enterprise/v1/enterprise-catalogs":
    $ref: "https://raw.githubusercontent.com/edx/edx-enterprise/260055b/api.yaml#/endpoints/v1/enterpriseCustomerCatalogs"
  "/enterprise/v1/enterprise-catalogs/{uuid}":
    $ref: "https://raw.githubusercontent.com/edx/edx-enterprise/260055b/api.yaml#/endpoints/v1/enterpriseCustomerCatalogByUuid"
  "/enterprise/v1/enterprise-catalogs/{uuid}/course-runs/{course_run_id}":
    $ref: "https://raw.githubusercontent.com/edx/edx-enterprise/260055b/api.yaml#/endpoints/v1/enterpriseCustomerCatalogCourseRunByUuid"
  "/enterprise/v1/enterprise-catalogs/{uuid}/courses/{course_key}":
    $ref: "https://raw.githubusercontent.com/edx/edx-enterprise/260055b/api.yaml#/endpoints/v1/enterpriseCustomerCatalogCourseByKey"
  "/enterprise/v1/enterprise-catalogs/{uuid}/programs/{program_uuid}":
    $ref: "https://raw.githubusercontent.com/edx/edx-enterprise/260055b/api.yaml#/endpoints/v1/enterpriseCustomerCatalogProgramByUuid"
  "/enterprise/v1/enterprise-customer/{uuid}/course-enrollments":
    $ref: "https://raw.githubusercontent.com/edx/edx-enterprise/260055b/api.yaml#/endpoints/v1/enterpriseCustomerCourseEnrollments"
  "/enterprise/v1/enterprise-customer/{uuid}/learner-summary":
    $ref: "https://raw.githubusercontent.com/edx/edx-enterprise-data/8fc95e4/api.yaml#/endpoints/v1/enterpriseCustomerLearnerSummary"

  # Registrar API Proxy
  # Note: There's an unresolved issue involving trailing slashes with proxy integrations in API Gateway.
  # Apparently all trailing slashes included in the value of {proxy} are trimmed, see this AWS
  # support forum thread: https://forums.aws.amazon.com/thread.jspa?messageID=749625
  # Our registrar API endpoint paths require trailing slashes, but other registrar paths, like those
  # under /static, cannot have them.  Thus, we've broken apart the different path types under registrar.
  # This means that this specification must be updated each time a new version of the
  # registrar API is released.

  "/registrar/api-docs":
    x-amazon-apigateway-any-method:
      x-amazon-apigateway-integration:
        type: "http_proxy"
        uri: "https://${stageVariables.registrar_host}/api-docs/"
        httpMethod: "ANY"

  "/registrar/login":
    x-amazon-apigateway-any-method:
      x-amazon-apigateway-integration:
        type: "http_proxy"
        uri: "https://${stageVariables.registrar_host}/login/"
        httpMethod: "ANY"

  "/registrar/logout":
    x-amazon-apigateway-any-method:
      x-amazon-apigateway-integration:
        type: "http_proxy"
        uri: "https://${stageVariables.registrar_host}/logout/"
        httpMethod: "ANY"

  "/registrar/static/{proxy+}":
    x-amazon-apigateway-any-method:
      parameters:
      - name: "proxy"
        in: "path"
      x-amazon-apigateway-integration:
        type: "http_proxy"
        uri: "https://${stageVariables.registrar_host}/static/{proxy}"
        httpMethod: "ANY"
        requestParameters:
          integration.request.path.proxy: "method.request.path.proxy"

  "/registrar/v1/{proxy+}":
    x-amazon-apigateway-any-method:
      parameters:
      - name: "proxy"
        in: "path"
      x-amazon-apigateway-integration:
        type: "http_proxy"
        uri: "https://${stageVariables.registrar_host}/api/v1/{proxy}/"
        httpMethod: "ANY"
        requestParameters:
          integration.request.path.proxy: "method.request.path.proxy"

  "/registrar/v1-mock/{proxy+}":
    x-amazon-apigateway-any-method:
      parameters:
      - name: "proxy"
        in: "path"
      x-amazon-apigateway-integration:
        type: "http_proxy"
        uri: "https://${stageVariables.registrar_host}/api/v1-mock/{proxy}/"
        httpMethod: "ANY"
        requestParameters:
          integration.request.path.proxy: "method.request.path.proxy"

# edX extension point. Lists the vendors in use and their specific
#  parameters that are expected by upstream refs.
# Upstream API owners: document your dependencies in this index file to
#  avoid conflicts with other upstreams.
x-edx-api-vendors:
  aws_apigateway:
    stage_variables:
    - "id"
    - "landing_page"
    - "edxapp_host"
    - "discovery_host"
    - "enterprise_host"
    - "gateway_host"
    - "analytics_api_host"
    - "registrar_host"
