# Swagger specification for the Studio content API

---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Studio content"
host: "your-open-edx-site.org"
basePath: "/contentstore/v1"
schemes:
- "https"

# Complete set of whitelisted routes for use with Studio content API
paths:

  # Index
  "/":
    $ref: "./index.yaml#/endpoints/index"

  # Heartbeat
  "/heartbeat":
    $ref: "./heartbeat.yaml#/endpoints/heartbeat"

  # OAuth2
  "/oauth2/v1/access_token":
    $ref: "./oauth.yaml#/endpoints/request_access_token"

  # Studio content API
  "/file_assets/{proxy+}":
    x-amazon-apigateway-any-method:
      parameters:
      - name: "proxy"
        in: "path"
      x-amazon-apigateway-integration:
        type: "http_proxy"
        uri: "https://${stageVariables.studio_host}/api/contentstore/v1/file_assets/{proxy}"
        httpMethod: "ANY"
        requestParameters:
          integration.request.path.proxy: "method.request.path.proxy"

  "/videos/uploads/{proxy+}":
    x-amazon-apigateway-any-method:
      parameters:
      - name: "proxy"
        in: "path"
      x-amazon-apigateway-integration:
        type: "http_proxy"
        uri: "https://${stageVariables.studio_host}/api/contentstore/v1/videos/uploads/{proxy}"
        httpMethod: "ANY"
        requestParameters:
          integration.request.path.proxy: "method.request.path.proxy"

  "/videos/images/{proxy+}":
    x-amazon-apigateway-any-method:
      parameters:
      - name: "proxy"
        in: "path"
      x-amazon-apigateway-integration:
        type: "http_proxy"
        uri: "https://${stageVariables.studio_host}/api/contentstore/v1/videos/images/{proxy}"
        httpMethod: "ANY"
        requestParameters:
          integration.request.path.proxy: "method.request.path.proxy"

  "/video_transcripts/{proxy+}":
    x-amazon-apigateway-any-method:
      parameters:
      - name: "proxy"
        in: "path"
      x-amazon-apigateway-integration:
        type: "http_proxy"
        uri: "https://${stageVariables.studio_host}/api/contentstore/v1/video_transcripts/{proxy}"
        httpMethod: "ANY"
        requestParameters:
          integration.request.path.proxy: "method.request.path.proxy"

  "/xblock/{proxy+}":
    x-amazon-apigateway-any-method:
      parameters:
      - name: "proxy"
        in: "path"
      x-amazon-apigateway-integration:
        type: "http_proxy"
        uri: "https://${stageVariables.studio_host}/api/contentstore/v1/xblock/{proxy}"
        httpMethod: "ANY"
        requestParameters:
          integration.request.path.proxy: "method.request.path.proxy"

